### ISSUE TITLE
steam achievements

### ISSUE THREAD

**Issue by headshotczech** [cornelisdemooij/AchievementVisualisation#1]
Hello,

I am very interested about Steam achievements and hunting
and little thinking if you can do "simple", "lightweight" program in C#, 
what can do this two things without crash game overlay:

- Edit custum sound of Achievement notification popup (or default from choose ps4/xbox trophy sound)
- Edit notification toast or do better notification (bigger, other design etc.)

But mainly just option to enable future of Steam achievement sound.

If this working and be great application, you can have more people of community, many people need this function long time.

If you can do this i can send you some donate as thanks for your good work of course.

Thank you for reply.

**Comment by cornelisdemooij** [comment]
Hi,

Sadly it appears to be the case that Steam doesn't support such modifications. The Steam API only lets you retrieve information about games and users; intercepting achievement notifications doesn't seem to be possible. 

Steam does have a suggestion forum: https://steamcommunity.com/discussions/forum/10/
Perhaps they will add support for mods for achievement notifications if you and other users let them know that you are excited about this functionality.

With regards,

Cornelis
